//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloVistaControlador_MVC_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cliente { get; set; }
        public string nom_cliente { get; set; }
        public string Apellido_cliente { get; set; }
        public Nullable<long> telefono { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
