//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloVistaControlador_MVC_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajadores
    {
        public int id_trabajador { get; set; }
        public string nom_trabajador { get; set; }
        public string area_especialidad { get; set; }
        public Nullable<int> años_experiencia { get; set; }
        public Nullable<int> grupo_trabajo { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
